# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('kpi', 'KPI Card'), ('table', 'Data Table'), ('text', 'Text / Note'), ('insights', 'AI Insights')], max_length=20)),
                ('size', models.CharField(choices=[('1x1', 'Small (1×1)'), ('2x1', 'Medium (2×1)'), ('3x1', 'Wide (3×1)'), ('2x2', 'Large (2×2)')], default='2x1', max_length=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('refresh_mins', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='analyser.chartconfig')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analyser.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
