# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='Nexyza', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('primary_color', models.CharField(default='#7c3aed', max_length=7)),
                ('accent_color', models.CharField(default='#3b82f6', max_length=7)),
                ('bg_color', models.CharField(default='#0d0b17', max_length=7)),
                ('surface_color', models.CharField(default='#1e1b2e', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('hide_datalens_branding', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=253)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
