# Generated by ChatGPT
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('collaboration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collabcomment',
            name='chart_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collabcomment',
            name='section_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CollabAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_ref', models.CharField(blank=True, max_length=255)),
                ('section_ref', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collab_actions', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collab_actions', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_actions', to='analyser.fileupload')),
            ],
            options={'ordering': ['status', '-created_at']},
        ),
    ]
