# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_column', models.CharField(max_length=255)),
                ('value_column', models.CharField(max_length=255)),
                ('periods', models.PositiveSmallIntegerField(default=6)),
                ('method', models.CharField(choices=[('linear', 'Linear Trend'), ('moving_avg', 'Moving Average'), ('exponential', 'Exponential Smoothing'), ('ai', 'AI-Powered (Claude)')], default='ai', max_length=20)),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('ai_narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='analyser.fileupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
