# Generated by Django 5.0.4 on 2026-04-16 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Shown in listing + meta description', max_length=400)),
                ('content', models.TextField(help_text='Markdown or HTML')),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('product', 'Product Update'), ('analytics', 'Data & Analytics'), ('tips', 'Tips & Tricks'), ('case-study', 'Case Study')], default='analytics', max_length=20)),
                ('cover_image', models.URLField(blank=True, help_text='Absolute URL to cover image')),
                ('og_image', models.URLField(blank=True, help_text='Override OG image (defaults to cover_image)')),
                ('author_name', models.CharField(default='Nexyza Team', max_length=80)),
                ('author_avatar', models.URLField(blank=True)),
                ('reading_time', models.PositiveSmallIntegerField(default=5, help_text='Minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
