# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('analysis', models.JSONField()),
                ('row_count', models.PositiveIntegerField()),
                ('column_count', models.PositiveIntegerField()),
                ('diff_from_prev', models.JSONField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analyser.fileupload')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('upload', 'version')},
            },
        ),
    ]
