# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Joined Dataset', max_length=100)),
                ('left_key', models.CharField(max_length=255)),
                ('right_key', models.CharField(max_length=255)),
                ('join_type', models.CharField(choices=[('inner', 'Inner Join'), ('left', 'Left Join'), ('right', 'Right Join'), ('outer', 'Outer Join')], default='inner', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins_as_left', to='analyser.fileupload')),
                ('result_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_join', to='analyser.fileupload')),
                ('right_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins_as_right', to='analyser.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
