# Generated by Django 5.0.4 on 2026-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='token',
            field=models.CharField(default='irtGRdVi0j25S3nwb2HKVUQ1U3O6VNW8Xgn6j7me', max_length=40, unique=True),
        ),
    ]
