# Generated by Django 5.0.4 on 2026-04-16 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('domain', models.CharField(blank=True, help_text='e.g. Finance, Marketing', max_length=50)),
                ('source_type', models.CharField(choices=[('manual_upload', 'Manual Upload'), ('pipeline', 'Pipeline'), ('api', 'API'), ('join', 'File Join')], default='manual_upload', max_length=20)),
                ('source_detail', models.TextField(blank=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Contains PII or confidential data')),
                ('refresh_frequency', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_assets', to=settings.AUTH_USER_MODEL)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entry', to='analyser.fileupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transform', models.CharField(choices=[('join', 'File Join'), ('clean', 'Data Cleaning'), ('formula', 'Computed Column'), ('pipeline', 'Pipeline Refresh'), ('export', 'Export')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineage_inputs', to='analyser.fileupload')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_outputs', to='analyser.fileupload')),
            ],
        ),
    ]
